frappe.pages["pridict-assets"].on_page_load=(wrapper)=>{frappe.pridict_assets=new PridictAssets(wrapper);};frappe.pages["pridict-assets"].on_page_show=()=>frappe.pridict_assets?.refresh();
class PridictAssets{
	constructor(wrapper){this.page=frappe.ui.make_app_page({parent:wrapper,title:__("Assets"),single_column:true});this.company=frappe.defaults.get_user_default("Company");$(wrapper).addClass("pridict-assets-page");this.$root=$('<div class="pridict-assets" aria-live="polite"></div>').appendTo(this.page.main.empty());this.loading();}
	async refresh(){this.loading();try{this.data=await frappe.xcall("pridict.pridict.page.pridict_assets.pridict_assets.get_overview",{company:this.company});this.company=this.data.filters?.company||this.company;this.render();}catch(_error){this.error();}}
	loading(){this.$root.html(`<div class="pridict-assets-state"><span class="pridict-executive-spinner"></span><strong>${__("Loading Assets")}</strong><p>${__("Retrieving permitted asset activity.")}</p></div>`);}
	error(){this.$root.html(`<div class="pridict-assets-state"><strong>${__("Assets could not be loaded")}</strong><p>${__("No data was changed. Try again or open the standard Assets workspace.")}</p><button class="btn btn-primary" data-action="retry">${__("Try again")}</button></div>`);this.bind();}
	render(){if(!this.data.companies?.length){this.$root.html(`<div class="pridict-assets-state"><strong>${__("No company access")}</strong><p>${frappe.utils.escape_html(this.data.message||"")}</p></div>`);return;}this.$root.html(`<header class="pridict-assets-hero"><div><span>${__("Asset lifecycle")}</span><h1>${__("Assets")}</h1><p>${__("Manage capitalization, custody, movement, maintenance, repair, depreciation, and retirement.")}</p></div><label><span>${__("Company")}</span><select data-company>${this.data.companies.map((company)=>`<option value="${frappe.utils.escape_html(company.name)}" ${company.name===this.company?"selected":""}>${frappe.utils.escape_html(company.name)}</option>`).join("")}</select></label></header><section class="pridict-assets-metrics">${this.metrics()}</section><div class="pridict-assets-grid"><section class="pridict-assets-panel"><header><div><span>${__("Action required")}</span><h2>${__("Lifecycle work needing follow-up")}</h2></div><b>${this.data.attention.length}</b></header>${this.attention()}</section><div class="pridict-assets-stack"><section class="pridict-assets-panel"><header><div><span>${__("Reports")}</span><h2>${__("Asset analysis")}</h2></div></header><div class="pridict-assets-links">${this.reports()}</div></section><section class="pridict-assets-panel"><header><div><span>${__("Quick actions")}</span><h2>${__("Create asset record")}</h2></div></header><div class="pridict-assets-actions">${this.actions()}</div></section></div></div><section class="pridict-assets-panel"><header><div><span>${__("Recent activity")}</span><h2>${__("Latest permitted asset records")}</h2></div></header><div class="pridict-assets-activity">${this.activity()}</div></section><footer class="pridict-assets-footer"><span>${__("Values use the selected company currency; native depreciation and accounting remain authoritative.")}</span><button class="btn btn-link" data-route="assets">${__("Open standard Assets workspace")}</button></footer>`);this.bind();}
	metrics(){const rows=[["operating_assets","Operating assets","asset"],["assets_in_maintenance","In maintenance","asset"],["pending_repairs","Pending repairs","asset-repair"],["draft_movements","Draft movements","asset-movement"]];return rows.map(([key,label,route])=>`<button data-route="${route}"><span>${__(label)}</span><strong>${this.data.metrics[key]??"—"}</strong><small>${frappe.utils.escape_html(this.data.definitions[key]||"")}</small></button>`).join("");}
	attention(){if(!this.data.attention.length)return`<div class="pridict-assets-empty">${__("No asset records currently need follow-up.")}</div>`;return this.data.attention.map((row)=>`<button class="pridict-assets-row" data-doctype="${row.doctype}" data-name="${row.name}"><span><strong>${frappe.utils.escape_html(row.title)}</strong><small>${frappe.utils.escape_html([row.detail||row.name,row.status,row.date].filter(Boolean).join(" · "))}</small></span><b>${row.amount!==null&&row.amount!==undefined?format_currency(row.amount,this.data.filters.currency):""}</b></button>`).join("");}
	reports(){return this.data.reports.map((row)=>`<button data-route="${row.route}">${frappe.utils.icon("chart","sm")}<span>${frappe.utils.escape_html(row.label)}</span></button>`).join("");}
	actions(){return Object.entries(this.data.create_permissions).filter(([,allowed])=>allowed).map(([doctype])=>`<button class="btn btn-default" data-new-doctype="${doctype}">${frappe.utils.icon("add","sm")}<span>${__(doctype)}</span></button>`).join("")||`<div class="pridict-assets-empty">${__("You do not have permission to create asset records.")}</div>`;}
	activity(){if(!this.data.activity.length)return`<div class="pridict-assets-empty">${__("No permitted asset activity is available.")}</div>`;return this.data.activity.map((row)=>`<button data-doctype="${row.doctype}" data-name="${row.name}"><span><strong>${__(row.doctype)}</strong><small>${frappe.utils.escape_html([row.detail||row.name,row.status].filter(Boolean).join(" · "))}</small></span><b>${row.amount!==null&&row.amount!==undefined?format_currency(row.amount,this.data.filters.currency):""}</b><time>${frappe.datetime.prettyDate(row.modified)}</time></button>`).join("");}
	bind(){this.$root.find('[data-action="retry"]').on("click",()=>this.refresh());this.$root.find("[data-route]").on("click",(event)=>frappe.set_route(event.currentTarget.dataset.route));this.$root.find("[data-doctype][data-name]").on("click",(event)=>frappe.set_route("Form",event.currentTarget.dataset.doctype,event.currentTarget.dataset.name));this.$root.find("[data-new-doctype]").on("click",(event)=>frappe.new_doc(event.currentTarget.dataset.newDoctype));this.$root.find("[data-company]").on("change",(event)=>{this.company=event.currentTarget.value;this.refresh();});}
}
